version: "3.1"
services:
  stat-server:
    build: ewm-stats/stat-server
    image: java-explore-with-me-stat-server
    container_name: statApp
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/statsDb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    restart: on-failure

  stat-db:
    image: postgres:16.1
    container_name: statDb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/statDb:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  main-server:
    build: service
    image: service
    container_name: service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stat-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/mainDb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - STATS_SERVER_URL=http://stat-server:9090
    restart: on-failure

  main-db:
    image: postgres:16.1
    container_name: mainDb
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/mainDb:/var/lib/postgresql/data/

    environment:
      - POSTGRES_DB=mainDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345

    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
