version: "3.1"
services:
  stats-server:
    build: ewm-stat/stat-server
    image: java-explore-with-me-stats-server
    container_name: statsApp
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsDb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    restart: on-failure

  stats-db:
    image: postgres:16.1
    container_name: statsDb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/statsDb:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statsDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ewm-service
    image: java-explore-with-me-ewm-service
    container_name: ewmService
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/mainDb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - STATS_SERVER_URL=http://stats-server:9090
    restart: on-failure

  ewm-db:
    image: postgres:16.1
    container_name: ewmDb
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/ewmDb:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mainDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10